# Use the official Python image as the base image
FROM python:3.10-slim


# Install system dependencies
RUN apt-get update && apt-get install -y git-lfs && apt-get clean

# Copy the requirements file into the container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", ${PORT:-8080}]
CMD ["python", "main.py"]
